"""Project scaffolding used by `reddit-researcher init`.

Each scaffolder writes a small set of files under the project directory: a
`project.toml`, a starter `prompt.md`, and (for search mode) `terms.txt` and
`subreddits.txt`. Existing files are never overwritten unless `force=True`.

Prompts are sourced from the built-in template library in
`reddit_researcher.prompt_templates`. Pass `prompt_template=<name>` to pick one
explicitly; otherwise the scrape mode picks a sensible default.
"""

from __future__ import annotations

from pathlib import Path

from .prompt_templates import default_template_for, template_text
from .storage import slugify

TERMS_TEMPLATE = """\
# One search term per line. Lines starting with '#' are ignored.
# Replace with terms relevant to your research.
"""


SUBREDDITS_TEMPLATE = """\
# Optional allowlist. When present, search is restricted to these subreddits.
# Leave empty (or remove this file) to search all of Reddit.
"""


def _subreddit_project_toml(*, name: str, description: str, subreddit: str, model: str) -> str:
    return f"""\
# Generated by `reddit-researcher init`.
# See docs/architecture.md for the full config reference.

name = "{name}"
description = "{description}"

[scrape]
mode = "subreddit"
subreddit = "{subreddit}"
sort = "top"
time_filter = "month"
post_limit = 25
comment_limit = 10
pause_seconds = 1.0
max_retries = 5

[analyze]
model = "{model}"
prompt_file = "prompt.md"
chunk_char_limit = 12000
ollama_timeout_seconds = 600
"""


def _search_project_toml(*, name: str, description: str, model: str) -> str:
    return f"""\
# Generated by `reddit-researcher init`.
# See docs/architecture.md for the full config reference.

name = "{name}"
description = "{description}"

[scrape]
mode = "search"
terms_file = "terms.txt"
subreddits_file = "subreddits.txt"
exact_phrase = true
sort = "top"
time_filter = "all"
post_limit = 10
comment_limit = 3
pause_seconds = 1.5
max_retries = 5

[analyze]
model = "{model}"
prompt_file = "prompt.md"
chunk_char_limit = 12000
ollama_timeout_seconds = 600

# [relevance]
# keywords = ["interview", "podcast", "study"]
"""


def scaffold_project(
    *,
    project_dir: Path,
    mode: str,
    subreddit: str | None = None,
    terms: list[str] | None = None,
    subreddits: list[str] | None = None,
    model: str = "qwen3:8b",
    description: str = "",
    prompt_template: str | None = None,
    force: bool = False,
) -> list[Path]:
    """Create a new project folder.

    Returns the list of files written. Skips files that already exist unless
    `force=True`. `prompt_template` selects a built-in prompt by name; when None,
    a sensible default is chosen for the mode.
    """
    if mode not in {"subreddit", "search"}:
        raise ValueError(f"Invalid mode: {mode!r}. Must be 'subreddit' or 'search'.")
    if mode == "subreddit" and not subreddit:
        raise ValueError("mode='subreddit' requires --subreddit.")

    project_dir.mkdir(parents=True, exist_ok=True)
    name = project_dir.name
    written: list[Path] = []

    template_name = prompt_template or default_template_for(mode)
    prompt = template_text(template_name)

    if mode == "subreddit":
        body = _subreddit_project_toml(
            name=slugify(name),
            description=description or f"Research project for r/{subreddit}.",
            subreddit=subreddit or "",
            model=model,
        )
        files: list[tuple[Path, str]] = [
            (project_dir / "project.toml", body),
            (project_dir / "prompt.md", prompt),
        ]
    else:
        body = _search_project_toml(
            name=slugify(name),
            description=description or "Reddit search across one or more terms.",
            model=model,
        )
        terms_body = TERMS_TEMPLATE
        if terms:
            terms_body += "\n".join(terms) + "\n"
        subs_body = SUBREDDITS_TEMPLATE
        if subreddits:
            subs_body += "\n".join(subreddits) + "\n"
        files = [
            (project_dir / "project.toml", body),
            (project_dir / "prompt.md", prompt),
            (project_dir / "terms.txt", terms_body),
            (project_dir / "subreddits.txt", subs_body),
        ]

    for path, content in files:
        if path.exists() and not force:
            continue
        path.write_text(content, encoding="utf-8")
        written.append(path)

    return written
