"""Project scaffolding used by `reddit-researcher init`.

Each scaffolder writes a small set of files under the project directory: a
`project.toml`, a starter `prompt.md`, and (for search mode) `terms.txt` and
`subreddits.txt`. Existing files are never overwritten unless `force=True`.
"""

from __future__ import annotations

from pathlib import Path

from .storage import slugify

SUBREDDIT_PROMPT = """\
Identify the most common questions and recurring themes in this subreddit.

Focus on:
- recurring patterns rather than one-off anecdotes
- practical questions users keep asking
- uncertainty, confusion, or misinformation that keeps showing up

In the final answer:
- group similar items together
- rank the most common themes first
- include short representative examples when helpful, citing post or comment ids in brackets
- keep the tone analytical and evidence-aware
"""


SEARCH_PROMPT = """\
For each search term, determine whether the supplied Reddit posts and comments are meaningfully
about the named topic.

Cost-control rule:

- If a chunk has no meaningful evidence for the topic, write exactly one sentence beginning
  `Not relevant:` and stop. Do not add headings, summaries, or commentary for irrelevant chunks.

When the chunk does have meaningful discussion, output a Markdown section per term with:

- A concise relevance judgment.
- A summary of the Reddit context (which subreddits, what posts are about, why the term came up).
- A summary of the commentary: praise, criticism, recurring questions, anecdotes, disagreements.
- Representative post or comment ids in brackets when they support a point.

Use only the supplied Reddit content.
"""


TERMS_TEMPLATE = """\
# One search term per line. Lines starting with '#' are ignored.
# Replace with terms relevant to your research.
"""


SUBREDDITS_TEMPLATE = """\
# Optional allowlist. When present, search is restricted to these subreddits.
# Leave empty (or remove this file) to search all of Reddit.
"""


def _subreddit_project_toml(*, name: str, description: str, subreddit: str, model: str) -> str:
    return f"""\
# Generated by `reddit-researcher init`.
# See docs/architecture.md for the full config reference.

name = "{name}"
description = "{description}"

[scrape]
mode = "subreddit"
subreddit = "{subreddit}"
sort = "top"
time_filter = "month"
post_limit = 25
comment_limit = 10
pause_seconds = 1.0
max_retries = 5

[analyze]
model = "{model}"
prompt_file = "prompt.md"
chunk_char_limit = 12000
ollama_timeout_seconds = 600
"""


def _search_project_toml(*, name: str, description: str, model: str) -> str:
    return f"""\
# Generated by `reddit-researcher init`.
# See docs/architecture.md for the full config reference.

name = "{name}"
description = "{description}"

[scrape]
mode = "search"
terms_file = "terms.txt"
subreddits_file = "subreddits.txt"
exact_phrase = true
sort = "top"
time_filter = "all"
post_limit = 10
comment_limit = 3
pause_seconds = 1.5
max_retries = 5

[analyze]
model = "{model}"
prompt_file = "prompt.md"
chunk_char_limit = 12000
ollama_timeout_seconds = 600

# [relevance]
# keywords = ["interview", "podcast", "study"]
"""


def scaffold_project(
    *,
    project_dir: Path,
    mode: str,
    subreddit: str | None = None,
    terms: list[str] | None = None,
    subreddits: list[str] | None = None,
    model: str = "qwen3:8b",
    description: str = "",
    force: bool = False,
) -> list[Path]:
    """Create a new project folder.

    Returns the list of files written. Skips files that already exist unless
    `force=True`.
    """
    if mode not in {"subreddit", "search"}:
        raise ValueError(f"Invalid mode: {mode!r}. Must be 'subreddit' or 'search'.")
    if mode == "subreddit" and not subreddit:
        raise ValueError("mode='subreddit' requires --subreddit.")

    project_dir.mkdir(parents=True, exist_ok=True)
    name = project_dir.name
    written: list[Path] = []

    if mode == "subreddit":
        body = _subreddit_project_toml(
            name=slugify(name),
            description=description or f"Research project for r/{subreddit}.",
            subreddit=subreddit or "",
            model=model,
        )
        prompt = SUBREDDIT_PROMPT
        files: list[tuple[Path, str]] = [
            (project_dir / "project.toml", body),
            (project_dir / "prompt.md", prompt),
        ]
    else:
        body = _search_project_toml(
            name=slugify(name),
            description=description or "Reddit search across one or more terms.",
            model=model,
        )
        prompt = SEARCH_PROMPT
        terms_body = TERMS_TEMPLATE
        if terms:
            terms_body += "\n".join(terms) + "\n"
        subs_body = SUBREDDITS_TEMPLATE
        if subreddits:
            subs_body += "\n".join(subreddits) + "\n"
        files = [
            (project_dir / "project.toml", body),
            (project_dir / "prompt.md", prompt),
            (project_dir / "terms.txt", terms_body),
            (project_dir / "subreddits.txt", subs_body),
        ]

    for path, content in files:
        if path.exists() and not force:
            continue
        path.write_text(content, encoding="utf-8")
        written.append(path)

    return written
